CREATE DATABASE Locadora;

USE Locadora;

CREATE TABLE Empresas(
		idEmpresa	INT PRIMARY KEY IDENTITY,
		Nome		VARCHAR(255) NOT NULL
);

CREATE TABLE Marcas(
		idMarca		INT PRIMARY KEY IDENTITY,
		Nome		VARCHAR(255) NOT NULL
);

CREATE TABLE Clientes(
		idCliente	INT PRIMARY KEY IDENTITY,
		Nome		VARCHAR(255) NOT NULL,
		CPF			VARCHAR(11) NOT NULL 
);

CREATE TABLE Modelos(
		idModelo	INT PRIMARY KEY IDENTITY,
		Descrição	VARCHAR(255) NOT NULL,
		idMarca		INT FOREIGN KEY REFERENCES Marcas(idMarca)
);

CREATE TABLE Veículos(
		idVeiculo	INT PRIMARY KEY IDENTITY,
		idModelo	INT FOREIGN KEY REFERENCES Modelos(idModelo),
		Placa		VARCHAR (255) NOT NULL,
		idEmpresa	INT FOREIGN KEY REFERENCES Empresas(idEmpresa)
);

CREATE TABLE Alugueis(
		idAluguel	INT PRIMARY KEY IDENTITY,
		idCliente	INT FOREIGN KEY REFERENCES Clientes(idCliente),
		idVeiculo	INT FOREIGN KEY REFERENCES Veículos(idVeiculo),
		DataInicio	DATE,
		DataFim		DATE
);